### ISSUE TITLE
Running 2D_shape_approximation results with Javascript Error: IPython is not defined in cell [3]

### ISSUE THREAD

**Issue by tmaric** [AndreWeiner/machine-learning-applied-to-cfd#2]
The solution for this is [here](https://stackoverflow.com/questions/51922480/javascript-error-ipython-is-not-defined-in-jupyterlab), I think the issue is in this part of the code:

```
if IN_COLAB:
    %matplotlib inline
else:
    %matplotlib notebook
```

I am running the notebook locally, if I just use

`%matplotlib inline`

at the beginning of the cell, everything works. `print(IN_COLAB)` is `False`.

**Comment by AndreWeiner** [comment]
Jupyter-lab currently does not support the notebook backend for interactive plots.
For now, I modified the cell to inline the plot instead ([commit](https://github.com/AndreWeiner/machine-learning-applied-to-cfd/commit/35f3863d1a718517d36134fe5b1dce65bdd8fc21#diff-fba6a5dc39be466010f7c0462bc4187f)). In Jupyter-lab "%matplotlib widget" may allows for interactivity, [see here](https://github.com/matplotlib/jupyter-matplotlib/issues/66).

Thx for reporting the issue!

Cheers, Andre
