### ISSUE TITLE
Dear Andre

### ISSUE THREAD

**Issue by IT-five** [AndreWeiner/machine-learning-applied-to-cfd#4]
Hello, I want to train a network in predicting the steady state flow velocity vector field and pressure field ,so i run keras_steady_flow_predictor.py,in that I found that len(train_geometries) = 0, so there should be a problem with my data set path, and everything else succeeded. If you see it, please take a look at it. Thank you very much. I will put the error picture Link below，Thank you!
https://stshoueducn-my.sharepoint.com/:f:/g/personal/m210911561_st_shou_edu_cn/EiB_9KBrt99Cjms93It_h7ABbd4ZxsubKE86TQSo0B4e3w?e=fhfGRH

**Comment by AndreWeiner** [comment]
Hi @IT-five,
I am sorry, but I don't see how your question is related to this repository. This is not a general ML+CFD support website :-)
Best, Andre
